/**
 * Stats Report Generator
 * Compiles a comprehensive Markdown and printable report summarizing your complete cinematic history.
 */

export function generateMarkdownReport(stats) {
  if (!stats) return '';
  const { overview, ratings, genres, decades, directors, actors, actresses, countries, vsImdb, funStats, tasteProfile } = stats;

  const dateStr = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  return `# CineTrack • Personal Movie & Taste Report
Generated on: **${dateStr}**

---

## 1. Executive Summary
- **Total Titles Watched:** ${overview.totalWatched.toLocaleString()}
  - **Feature Movies:** ${overview.totalMovies.toLocaleString()}
  - **TV / Web Series:** ${overview.totalSeries.toLocaleString()}
  - **Anime Series & Films:** ${overview.totalAnime.toLocaleString()}
- **Queued in Watchlist:** ${overview.totalWatchlist.toLocaleString()} titles
- **Total Viewing Duration:** ${overview.totalHours.toLocaleString()} Hours (${overview.formattedDuration})
- **Personal Rating Average:** ★ **${overview.averageRating} / 10** across ${ratings.totalRated.toLocaleString()} ratings
- **Masterpieces (★ 10/10):** ${overview.perfect10Count} titles
- **Global Cinema Reach:** ${overview.totalCountriesCount} sovereign nations

---

## 2. Cinematic Persona & Taste Profile
> **Archetype:** ${tasteProfile.narrative}

---

## 3. Rating Distribution
| Score | Frequency | Percentage | Visual Bar |
| :--- | :---: | :---: | :--- |
${ratings.distribution.map(d => `| ★ ${d.rating} | ${d.count} | ${d.percentage}% | ${'█'.repeat(Math.round(d.percentage / 4))} |`).join('\n')}

---

## 4. Top Genres by Frequency & Score
| Genre | Titles Watched | Your Average Rating |
| :--- | :---: | :---: |
${genres.topByCount.map(g => `| **${g.genre}** | ${g.count} | ★ ${g.avgRating} |`).join('\n')}

---

## 5. Eras & Decades Explored
| Era / Decade | Titles Watched | Average Score |
| :--- | :---: | :---: |
${decades.map(d => `| **${d.decade}** | ${d.count} | ★ ${d.avgRating} |`).join('\n')}

---

## 6. Top Directors
| Director | Titles Watched | Average Rating | Sample Films |
| :--- | :---: | :---: | :--- |
${directors.map(d => `| **${d.name}** | ${d.count} | ★ ${d.avgRating} | ${d.sampleTitles || '—'} |`).join('\n')}

---

## 7. Leading Actors & Actresses
### Leading Actors
${actors.length > 0 ? actors.map(a => `- **${a.name}**: ${a.count} titles (Avg: ★ ${a.avgRating})`).join('\n') : '_Populates dynamically as TMDB enrichment completes._'}

### Leading Actresses
${actresses.length > 0 ? actresses.map(a => `- **${a.name}**: ${a.count} titles (Avg: ★ ${a.avgRating})`).join('\n') : '_Populates dynamically as TMDB enrichment completes._'}

---

## 8. World Cinema & Country Footprint
Total Nations Represented: **${countries.totalCount} Countries**

| Rank | Country | Titles Watched | Proportion |
| :---: | :--- | :---: | :---: |
${countries.topCountries.map((c, i) => `| #${i + 1} | ${c.country} | ${c.count} | ${c.percentage}% |`).join('\n')}

---

## 9. Your Rating vs. IMDb Consensus
- **Critic Alignment:** ${vsImdb.criticStyle}
- **Average Delta:** ${Number(vsImdb.avgDelta) > 0 ? `+${vsImdb.avgDelta}` : vsImdb.avgDelta} points vs. IMDb global score
- **Higher than IMDb:** ${vsImdb.higherCount} titles
- **Lower than IMDb:** ${vsImdb.lowerCount} titles

### Top Guilty Pleasures (Loved by you, overlooked by consensus)
${vsImdb.guiltyPleasures.map(g => `- **${g.title}** (${g.year || '—'}): You rated ★ **${g.your_rating}**, IMDb gave ★ **${g.imdb_rating.toFixed(1)}** (+${g.delta})`).join('\n')}

### Notable Hidden Gems (High rating with low voter count)
${vsImdb.hiddenGems.map(h => `- **${h.title}** (${h.year || '—'}): You rated ★ **${h.your_rating}** (${h.votes ? h.votes.toLocaleString() : 'few'} IMDb votes)`).join('\n')}

---

## 10. Extremes & Milestones
- **Longest Film Watched:** ${funStats.longestMovie ? `${funStats.longestMovie.title} (${funStats.longestMovie.runtime || funStats.longestMovie.imdb_runtime_mins} mins)` : '—'}
- **Oldest Classic Watched:** ${funStats.oldestMovie ? `${funStats.oldestMovie.title} (${funStats.oldestMovie.year || funStats.oldestMovie.imdb_year})` : '—'}
- **Newest Film Watched:** ${funStats.newestMovie ? `${funStats.newestMovie.title} (${funStats.newestMovie.year || funStats.newestMovie.imdb_year})` : '—'}

---
*Report generated by CineTrack • Personal Movie Tracker & Insights*
`;
}

/**
 * Downloads the Markdown report directly to user's device
 */
export function downloadMarkdownReport(stats) {
  const content = generateMarkdownReport(stats);
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `CineTrack_Movie_Report_${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Triggers standard browser print dialog styled for saving as PDF
 */
export function printPDFReport() {
  window.print();
}
